#include "vcd_writer.h"

#include <inttypes.h>

static void binary(FILE *file, unsigned value, unsigned width, char id)
{
    int bit;

    fputc('b', file);
    for (bit = (int)width - 1; bit >= 0; --bit) {
        fputc((value & (1u << bit)) != 0 ? '1' : '0', file);
    }
    fprintf(file, " %c\n", id);
}

bool vcd_open(VcdWriter *writer, const char *path, const Pic10F200 *cpu)
{
    writer->file = fopen(path, "w");
    writer->active = writer->file != NULL;
    if (!writer->active) {
        return false;
    }

    fprintf(writer->file,
            "$date generated by picemu $end\n"
            "$version PicEmu PIC10F200 $end\n"
            "$timescale 1us $end\n"
            "$scope module pic10f200 $end\n"
            "$var wire 9 ! pc $end\n"
            "$var wire 8 \" w $end\n"
            "$var wire 8 # status $end\n"
            "$var wire 8 $ tmr0 $end\n"
            "$var wire 4 %% gpio $end\n"
            "$var wire 1 & sleeping $end\n"
            "$var wire 1 0 gp0 $end\n"
            "$var wire 1 1 gp1 $end\n"
            "$var wire 1 2 gp2 $end\n"
            "$var wire 1 3 gp3 $end\n"
            "$upscope $end\n"
            "$enddefinitions $end\n");
    vcd_sample(writer, cpu);
    return true;
}

void vcd_sample(VcdWriter *writer, const Pic10F200 *cpu)
{
    uint8_t gpio;
    unsigned pin;

    if (!writer->active) {
        return;
    }

    gpio = pic10f200_gpio_value(cpu);
    fprintf(writer->file, "#%" PRIu64 "\n", cpu->cycles);
    binary(writer->file, cpu->pc, 9, '!');
    binary(writer->file, cpu->w, 8, '"');
    binary(writer->file, cpu->ram[PIC10_STATUS], 8, '#');
    binary(writer->file, cpu->ram[PIC10_TMR0], 8, '$');
    binary(writer->file, gpio, 4, '%');
    fprintf(writer->file, "%c&\n", cpu->sleeping ? '1' : '0');
    for (pin = 0; pin < 4; ++pin) {
        fprintf(writer->file, "%c%c\n",
                (gpio & (1u << pin)) != 0 ? '1' : '0',
                (char)('0' + pin));
    }
}

void vcd_close(VcdWriter *writer)
{
    if (writer->active) {
        fclose(writer->file);
    }
    writer->file = NULL;
    writer->active = false;
}
